name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew setupCiWorkspace
      - run: ./gradlew jar
      - uses: actions/upload-artifact@v1
        with:
          name: warpto-dev
          path: build/libs/warpto-1.0.jar
      - run: ./gradlew reobfJar
      - uses: actions/upload-artifact@v1
        with:
          name: warpto
          path: build/libs/warpto-1.0.jar